apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxdigit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linuxdigit
  template:
    metadata:
      labels:
        app: linuxdigit
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://10.240.0.4:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      containers:
      - name: amazonlinux
        image: amazonlinux:latest
        command: ["sh", "-c", "yum install httpd"]
        command: ["sh", "-c", "/usr/sbin/httpd","-D","FOREGROUND" ]
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
