apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      containers:
      - name: my-vault-server
        image: vault
        env:
        - name: VAULT_ADDR
          value: "https://vault:8200"
        - name: VAULT_SKIP_VERIFY
          value: "1"
        - name: VAULT_TOKEN
          value: "s.XBZc4rXIvigIGMHgqlkbNEJl"
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $VAULT_TOKEN | vault login -;done"]
        command: ["/bin/sh"]
        args: ["-c", "while true; do vault kv put secret/foo bar=baz; done"] 
